---
name: Release
kind: pipeline
type: docker

steps:
- name: publish
  image: otwld/drone-chart-releaser-github-pages
  settings:
    cr_token:
      from_secret: github_api_key
    skip_existing: true

trigger:
  event:
    - push
  branch:
    - master
