---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "component.fullname" . }}
  labels:
    {{- include "component.labels" . | nindent 4 }}
spec:
  {{- include "component.replicaCount" . | nindent 2 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "component.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "component.metricsAnnotations" .Values.metrics | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/config-cm.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "component.selectorLabels" . | nindent 8 }}
        {{- if .Values.extraLabels }}
          {{- toYaml .Values.extraLabels | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: clearport
          image: {{ include "component.image" .Values.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["clearport", "start", "app"]
          env:
            {{- with .Values.services.operatorWs }}
            - name: OPERATOR_WS_ADDR
              value: {{ default .port .internalPort | print | printf ":%s" }}
            {{- end }}
            {{- with .Values.services.operatorGrpc }}
            - name: OPERATOR_GRPC_PORT
              value: {{ default .port .internalPort | print | printf ":%s" }}
            {{- end }}
            {{- with .Values.services.peerGrpc }}
            - name: PEER_URL
              value: {{ default .port .internalPort | print | printf "http://%s:%s" $.Values.externalHostname }}
            {{- end }}
            - name: CHANNEL_SEND_TRANSACTIONS
              value: {{ .Values.responderMode.enabled | quote }}
          {{- if or .Values.secrets .Values.externalSecret }}
          envFrom:
          {{- if .Values.secrets }}
            - secretRef:
                name: {{ include "component.fullname" . }}-opt-env
          {{- end }}
          {{- if .Values.externalSecret }}
            - secretRef:
                name: {{ .Values.externalSecret }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
          {{- if .Values.persistentVolume.enabled }}
            - name: pv
              mountPath: {{ .Values.persistentVolume.mountPath }}
          {{- end }}
          {{- include "component.resources" . | nindent 10 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "component.fullname" . }}-config
      {{- with .Values.persistentVolume.enabled }}
        - name: pv
          persistentVolumeClaim:
            claimName: {{ include "component.fullname" $ }}
      {{- end }}
      {{- include "component.imagePullSecrets" . | nindent 6 }}
      {{- include "component.nodeSelectorLabels" . | nindent 6 }}
      {{- include "component.affinity" . | nindent 6 }}
      {{- include "component.tolerations" . | nindent 6 }}
