{{- range $name, $svc := .Values.services }}
{{- $svc = set $svc "name" $name }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "component.fullname" $ }}-{{ kebabcase $svc.name }}"
  labels:
    {{- include "component.labels" $ | nindent 4 }}
spec:
  type: {{ default "ClusterIP" $svc.type }}
  ports:
    {{- include "service.port" $svc | nindent 4 }}
  selector:
    {{- include "component.selectorLabels" $ | nindent 4 }}
{{- end }}
