apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "component.fullname" . }}-config
  labels:
    {{- include "component.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
data:
  finex.yaml: |-
    {{- .Values.config | nindent 4 }}
