replicaCount: 1

image:
  repository: quay.io/openware/openfinex
  tag: master
  pullPolicy: IfNotPresent

metrics:
   port: 8080
   enabled: true
   endpoint: "/metrics"

fullnameOverride: ""
nameOverride: ""

secrets: {}
externalSecret: ""

config: |
  mode: dev

services:
  ws:
    port: 8080
  grpc:
    type: NodePort
    # nodePort: 30000
    port: 50051

externalHostname: example.kayen.io
tlsClusterIssuer: letsencrypt-prod

ingress:
  path: /
  tls:
    enabled: true

cleanupHooksEnabled: false
hooks:
  createDb:
    enabled: true
    image:
      repository: supabase/postgres
      tag: 13.3.0
    secrets:
      - name: db-credentials
        envs:
          DATABASE_ROOT_USER: PGUSER
          DATABASE_ROOT_PASSWORD: PGPASSWORD
      - name: opt-env
        this_release: true
        envs:
          FINEX_DATABASE_NAME: DB_NAME
          FINEX_DATABASE_HOST: PGHOST
          FINEX_DATABASE_PORT: PGPORT
  createDbUser:
    enabled: true
    image:
      repository: supabase/postgres
      tag: 13.3.0
    secrets:
      - name: db-credentials
        envs:
          DATABASE_ROOT_USER: PGUSER
          DATABASE_ROOT_PASSWORD: PGPASSWORD
      - name: opt-env
        this_release: true
        envs:
          FINEX_DATABASE_USERNAME: DB_USER
          FINEX_DATABASE_PASSWORD: DB_PASS
          FINEX_DATABASE_NAME: DB_NAME
          FINEX_DATABASE_SCHEMA: DB_SCHEMA
          FINEX_DATABASE_HOST: PGHOST
          FINEX_DATABASE_PORT: PGPORT
  dropDbUser:
    enabled: true
    image:
      repository: supabase/postgres
      tag: 13.3.0
    secrets:
      - name: db-credentials
        envs:
          DATABASE_ROOT_USER: PGUSER
          DATABASE_ROOT_PASSWORD: PGPASSWORD
      - name: opt-env
        this_release: true
        envs:
          FINEX_DATABASE_USERNAME: DB_USER
          FINEX_DATABASE_NAME: DB_NAME
          FINEX_DATABASE_HOST: PGHOST
          FINEX_DATABASE_PORT: PGPORT
  dropDb:
    enabled: true
    image:
      repository: supabase/postgres
      tag: 13.3.0
    secrets:
      - name: db-credentials
        envs:
          DATABASE_ROOT_USER: PGUSER
          DATABASE_ROOT_PASSWORD: PGPASSWORD
      - name: opt-env
        this_release: true
        envs:
          FINEX_DATABASE_NAME: DB_NAME
          FINEX_DATABASE_HOST: PGHOST
          FINEX_DATABASE_PORT: PGPORT
  createDbSchema:
    enabled: true
  migrateDbSchema:
    enabled: true
  seedInfluxDb:
    enabled: true
    image:
      repository: "influxdb"
      tag: "1.8.10-alpine"
    secrets:
      - name: opt-env
        this_release: true
        envs:
          FINEX_INFLUX_HOST: INFLUXDB_HOSTS

nodeSelector: {}

tolerations: []

affinity: {}

profile:
  enabled: false
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

probes:
  readiness: {}
  liveness: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

extraLabels: {}
